// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    Popover: typeof import("@headlessui/vue")["Popover"];
    PopoverButton: typeof import("@headlessui/vue")["PopoverButton"];
    PopoverPanel: typeof import("@headlessui/vue")["PopoverPanel"];
  }
}

export {};
