// Generated by 'unplugin-auto-import'
export {}
declare global {
  const defineArticle: typeof import('@vueuse/schema-org/runtime')['defineArticle']
  const defineBreadcrumb: typeof import('@vueuse/schema-org/runtime')['defineBreadcrumb']
  const defineComment: typeof import('@vueuse/schema-org/runtime')['defineComment']
  const defineEvent: typeof import('@vueuse/schema-org/runtime')['defineEvent']
  const defineHowTo: typeof import('@vueuse/schema-org/runtime')['defineHowTo']
  const defineImage: typeof import('@vueuse/schema-org/runtime')['defineImage']
  const defineLocalBusiness: typeof import('@vueuse/schema-org/runtime')['defineLocalBusiness']
  const defineOrganization: typeof import('@vueuse/schema-org/runtime')['defineOrganization']
  const definePerson: typeof import('@vueuse/schema-org/runtime')['definePerson']
  const defineProduct: typeof import('@vueuse/schema-org/runtime')['defineProduct']
  const defineQuestion: typeof import('@vueuse/schema-org/runtime')['defineQuestion']
  const defineReadAction: typeof import('@vueuse/schema-org/runtime')['defineReadAction']
  const defineRecipe: typeof import('@vueuse/schema-org/runtime')['defineRecipe']
  const defineReview: typeof import('@vueuse/schema-org/runtime')['defineReview']
  const defineSearchAction: typeof import('@vueuse/schema-org/runtime')['defineSearchAction']
  const defineVideo: typeof import('@vueuse/schema-org/runtime')['defineVideo']
  const defineWebPage: typeof import('@vueuse/schema-org/runtime')['defineWebPage']
  const defineWebSite: typeof import('@vueuse/schema-org/runtime')['defineWebSite']
  const useSchemaOrg: typeof import('@vueuse/schema-org/runtime')['useSchemaOrg']
}
